### ISSUE TITLE
feat/change layer id to uuid to ensure unique.

### ISSUE THREAD

**Issue by leeduckgo** [qgpcybs/jimu#4]

**Comment by qgpcybs** [comment]
Very good advice. Referring to the practice of mature engines like Unity, it is also necessary to use UUID for object management. 
Some of my thoughts:

1. Layer is currently treated as a type of object, UUID can be an attribute of object, not only limited to layer.
2. The existing ID will be more intuitive, in the habit of many game developers, they are more accustomed to searching for objects based on ID or name than based on UUID. ID can be kept as a non-primary key.
